name: deploy pipe

on:
  push:
    tags:
      - v*
    branch:
      - main

jobs:
  build:
    name: Build and deploy Pipe
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Login to docker.io registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build image and push to Docker Hub 
      uses: docker/build-push-action@v5
      with:
        context: .
        tags: |
          wollomatic/trivy-pipe:latest 
          wollomatic/trivy-pipe:${{github.ref_name}}
        push: true